### ISSUE TITLE
`tricom` directory in components

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/ng-boilerplate#1]
I'd like to propose we add a `tricom` directory to the root `src` directory. This would be components that "come with" the boilerplate. I'd also like to propose we integrate webpack into the gulp workflow. This way these components can be included in the compiled JS file as needed. Tests should also be written for these. We will need to consider how to integrate the Sass (this could be as simple as importing the sass file to the core `app.scss` file).

**Pros** We tuck away the "built-in" components from the app-specific components, only pulling them in as they are needed. Webpack is becoming a modern standard, and may be a more efficient way to pull in dependencies. Automatic testing on built-in components can be more easily separated from any app-specific tests.

**Cons** Honestly can't think of any.

**Comment by Taylord93** [comment]
Oh gotcha. I misunderstood. Im all for it then. We will just need to compile a list. And essentially, for the second part, we would be looking at creating an entire tricom front-end framework, correct? Then load in some kind of theme file based on which client were building for?

**Comment by Toddses** [comment]
Well I'm not sure we'd ever have much use for a full-on front-end framework. My bet is that most of our work will require custom styling and the like, which makes creating a theme-able framework somewhat dubious. I do see value in some re-usable and theme-able components, but I think we should be pretty picky about what to include here. Perhaps we should table that discussion for the moment and address it when it seems clearer that this type of component would be useful.

**Comment by Taylord93** [comment]
Agreed. Leaving the issue open for now...
