### ISSUE TITLE
Create a generator

### ISSUE THREAD

**Issue by Taylord93** [TricomB2B/ng-boilerplate#11]
I feel this would heavily benefit from a command line generator. Yeoman seems to be the simplest and quickest way to get this set up, so once we have some extra time I'll dive in and look for other options.

**Comment by Toddses** [comment]
I've done some work with Yeoman in the past. Its not too hateful to build a generator using a git repo as the source. That said if you find yourself pretty much just using yeoman to clone the repo with no additional functionality, I'd say drop it.

What I'd really like to see is the ability to do a command like

```sh
$ someapp generate directive prefix-example
```

This would generate the directive in the right spot with the files

```
prefix-example.directive.js
prefix-example.html
prefix-example.scss
```

And populate the files with a starter template for directives. We'd have a generator for each type of component. I believe this is something yeoman can facilitate but it's been a while.

**Comment by Taylord93** [comment]
Yes I agree, that would be super helpful. From what I've seen so far in Yeoman, you can run additional commands with something like this: `yo generate tricom:directive directive-name`, we could of course use a node-based option. or maybe something like Laravels [artisan](https://laravel.com/docs/5.2/artisan). Yeoman just had a "generator generator" which would speed up the process, but if we're going to do it then lets do it exactly how we want.

**Comment by Toddses** [comment]
Pretty sure Yeoman is node anyway. Seems like it's the way to go for what we're looking for.

**Comment by Toddses** [comment]
I kinda think we should move the Yeoman Generator to a separate repo. I suppose this is a task for whenever we get back to implementing the generator(s).

**Comment by Toddses** [comment]
We've started a generator repo.
