### ISSUE TITLE
drop components in favor of more specific subdirectories

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/ng-boilerplate#19]
eg we'd have a `directives`, `factories`, `views` instead of a generic `components`

**Comment by Toddses** [comment]
worked pretty well for me on Emerson, but I think we're doing this already with the generator, and we're favoring that a bit at the moment because of the templating...

**Comment by Taylord93** [comment]
Yeah we need to update this to reflect what the generator puts out. May work on this later today...
