### ISSUE TITLE
sample app can just be essentially documentation

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/ng-boilerplate#2]
So I think we can set up the index.html to just be documentation of the "built-in" components. We can just set up examples of each component and how they might be used. Additional relevant documentation can also be included.

**Pros** We document each component individually and provide examples on how they could or should be used. Opportunity for additional examples or documentation.

**Cons** Technically it's not an app so we won't have an example of "real world" usage that we might get from a small app.

**Comment by Taylord93** [comment]
I agree, but still good to keep on the radar in the event that we hit a slow spell. Maybe as a solution for now we should create an `example` directory or file where we can look at the documentation (that we still need to make) for everything.
